---
title: "Science Communication Data Cleanup and Joins"
output: html_notebook
date: 2020-04-22
---

```{r}
library(tidyverse)
final_surv<-read.csv("~/Documents/projects/scicomm_analysis_Arik/data/scicomm_final_survey_numeric.csv",na.strings=c("","NA"))
initial_surv<-read.csv("~/Documents/projects/scicomm_analysis_Arik/data/scicomm_initial_survey.csv",na.strings=c("","NA"))
grades<-read.csv("~/Documents/projects/scicomm_analysis_Arik/data/scicomm_course_grades.csv",na.strings=c("","NA"))
groups<-read.csv("~/Documents/projects/scicomm_analysis_Arik/data/scicomm_group_assgn.csv",,na.strings=c("","NA"))

```

### Data cleanup / filtering 

```{r join grades and groups}
#group together grades data with group assignment to get sis_id and group assignment 
#inner join: only select students that are in groups and grades. 
disc_grades<-inner_join(grades,groups,by = "id") #n = 211

#group sample size check (how many students per group?)
disc_grades %>%
  group_by(group) %>% tally() #109 control, 102 treatment
```

```{r filter by reflection responses}
#filtering by reflection responses 

#add columns on whether student completed each response 
disc_grades<-disc_grades %>%
  mutate(r1 = ifelse(!is.na(response_1),1,0), #(1 = completed, 0 = not completed)
         r2 = ifelse(!is.na(response_2),1, 0),
         r3 = ifelse(!is.na(response_3),1, 0),
         r4 = ifelse(!is.na(response_4),1, 0),
         r5 = ifelse(!is.na(response_5),1, 0)) %>%
        rowwise %>%  #for each row, count how many responses complete
         mutate(response_count = sum(r1, r2,r3,r4,r5))

#filter the dataframe by those that completed 3 or more responses
disc_grades <- disc_grades %>%
  filter(response_count >= 3) 

#updated sample size (now 192 students, 98 control, 94 treatment)
disc_grades %>%
  group_by(group) %>% tally()

```
### Evaluation criteria 
Filtered out observations that took less than 3 minutes to take the survey or entered a mismatching student id (making accurate joins difficult).

```{r survey filtering}
#rename student_id column to sis_id in survey dataframes
initial_surv<-rename(initial_surv, sis_id = student_id)
final_surv<-rename(final_surv, sis_id = student_id)

#sample size check
initial_surv %>% filter(!is.na(sis_id)) %>% tally()   #214 obs. (more than students!)
final_surv %>% filter(!is.na(sis_id)) %>% tally() #112 obs. 

#filter out observations that took less than 3 minutes to take survey 
initial2<-initial_surv %>%
  filter(duration_sec > 180)   #131 observations
final2<-final_surv %>%
  filter(duration_sec > 180) #82 observations
```

```{r survey joins}
#begin joins 

#convert columns we are joining by (sis_id) to characters
disc_grades$sis_id<-as.character(disc_grades$sis_id)
initial2$sis_id<-as.character(initial2$sis_id)
final2$sis_id<-as.character(final2$sis_id)

#SANITY CHECK
#inner join: only those in pre that have grades/group assignments 
pre_inner<-inner_join(initial2, disc_grades, by = "sis_id") #now 113 (out of 131)
post_inner<-inner_join(final2, disc_grades, by = "sis_id") #now 80 (out of 82)

#anti join shows who the individuals are that do not have grades/group assignments
pre_missing_group<-anti_join(initial2, disc_grades, by = "sis_id") #18 
post_missing_group<-anti_join(final2,disc_grades, by = "sis_id") #only 2 
```

```{r check for duplicates}
#check for duplicates
  #the following students have duplicate student ids in pre (n = 3)
duplicates_pre<- pre_inner %>% 
  group_by(sis_id) %>%
  summarise(n = n()) %>%
  filter(n > 1) %>%
  pull(sis_id)

#view the students' dataframe with duplicates in pre
pre_inner %>%
  filter(sis_id %in% duplicates_pre)

  #the following students have duplicate student ids in post (n = 1)
duplicates_post<- post_inner %>% 
  group_by(sis_id) %>%
  summarise(n = n()) %>%
  filter(n > 1) %>%
  pull(sis_id)

#view the students'with duplicates in post
post_inner %>%
  filter(sis_id %in% duplicates_post)
```

```{r remove duplicates before stack}

#remove duplicates in each survey dataframe before stacking 

`%notin%` <- Negate(`%in%`) #creates negate function 

#remove all surveys with duplicate ids in pre
pre_cleaned<- pre_inner %>%
  filter(sis_id %notin% duplicates_pre) #lose 6 obs. (113 --> 107)

#remove all surveys with duplicate ids in post
post_cleaned<- post_inner %>%
  filter(sis_id %notin% duplicates_post) #lose 2 obs. (80 --> 78)

#can also use anti_join to see data for removed students with duplicates. 
    #anti_join(pre_inner, pre_cleaned, by ="sis_id") 
```

```{r stack pre and post}
#next: stack together pre and post into one data frame using rbind

#create survey column in both to be combined
pre_cleaned$survey<-"pre"
post_cleaned$survey<-"post"

#remove columns that only appear in the final survey (will reappend later)
post_only_cols <-post_cleaned %>% select(sis_id,assignment, future_assgn, comments)
post_cleaned<- post_cleaned %>% select(-assignment, -future_assgn, -comments)

#check to be sure column names match before stacking
colnames(pre_cleaned) == colnames(post_cleaned) #all should be TRUE

#stack the two dataframes together
pre_post<-rbind(pre_cleaned,post_cleaned) 

#sample size check : 
  #how many pre and post? (should be 107 pre, 78 post = 185 surveys) 
pre_post %>%
  group_by(survey) %>%
  summarise(individuals = n_distinct(sis_id)) 

  #how many treatment and control? (n = 69 control, 66 treat, = 135 individuals)
pre_post %>%
  group_by(group, survey) %>%
  summarise(individuals = n_distinct(sis_id))  

#create variable that checks if an individual has both surveys
pre_post<-pre_post %>%
  group_by(sis_id) %>%
  mutate(n = n()) %>%
  ungroup()%>%
  mutate(both_surveys = case_when( n > 1 ~ "y", n <= 1 ~ "n")) %>%
  select(-n)

#sample size of those with both pre and post surveys
  pre_post %>%
      group_by(group, both_surveys) %>%
      summarise(individuals= n_distinct(sis_id)) 
  
```

```{r import demographic data}
#add demographic data 
dem<-read.csv("~/Documents/projects/scicomm_analysis_Arik/data/raw_data_from_Arik/NPB101_sp2019_demographics.csv")

#need to get sis_id into groups
groups_sis<-inner_join(groups,grades, by = "id")

#select only the sis_id, section, group data for join
groups_sis<-groups_sis %>% 
  select(id, sis_id, section.x, login_id,group) %>% 
  rename(section = section.x)

#rename vars for join 
dem<-dem %>% rename(sis_id = sid)

#get demographics for grouped discussion students only (inner_join)
disc_dem<-inner_join(dem, groups_sis, by = c("sis_id")) #it works! 211 obs. 
```

```{r join with demographic data}

#convert joining variable (sis_id) to same class
disc_dem$sis_id<-as.character(disc_dem$sis_id)
pre_post$sis_id<-as.character(pre_post$sis_id)

#inner join of pre_post with demographics
pre_post_dem <- inner_join(pre_post, disc_dem, by = c("sis_id"))


#clean up the final join to get rid of duplicate columns 
test<-pre_post_dem %>% 
  select(-id.y, -login_id.y, -group.y, -sis_id_2, -X, -r1, -r2, -r3, -r4, -r5, -section.y,-full_name.y) %>%
  rename(login_id = login_id.x, group = group.x, section = section.x, id_2 = id.x, full_name = full_name.x)
```



```{r for within-groups}
#get students with both (n= 100)
both_surveys<-pre_post %>%
  filter(both_surveys == "y")

#NEED TO CALCULATE CHANGE. 

#remove unneccesary columns 
within_subj <-
both_surveys %>%
  select(-start_date, -end_date, -status,-ip_address,-progress, -duration_sec, -finished, -recorded_date, -response_id,-full_name.y, -sis_id_2, -X, -login_id, -final, -mt1, -mt2, -mt3, -grade_final, -letter_grade, -section.y, -both_surveys, -name, -sis_login_id, -first_name, -last_name)

#convert to true long format 
within_subj <- within_subj %>%
  pivot_longer(cols = scientist:interested,
               names_to = "question", 
               values_to = "score") 

#sample size sanity check 
  #should match, both 24 control, 26 treat.
both_surveys %>% group_by (group) %>% summarise(indivs = n_distinct(sis_id)) 

within_subj %>%
  group_by(group) %>%
  summarise(indivs = n_distinct(sis_id)) 


#create dataframe with pre, post, and difference scores for within-subj 
within_diff<-
within_subj %>%
  group_by(id, question) %>% #should only be two observations in each pair (pre and post)
  mutate(next_score = lead(score, order_by=id)) %>% #for each pre question, annotates the post score in next_score column
  filter(survey == "pre") %>% #trim to only pre, as lead only works for pre.
  rename(pre_score = score,   #rename score to pre-score
         post_score = next_score) %>% #rename next-score to post-score
  rowwise() %>% 
  mutate(diff_score = post_score - pre_score) %>% #for each row, calculate post-pre across cols
  select(-survey) #delete now-meaningless survey col

#sample size check (still matches)
within_diff %>%       
  group_by(group) %>%        
  summarise(indivs = n_distinct(sis_id))  
```

```{r write to csv}
#send final, joined dataset to a csv file (ONLY RUN ONCE)
write.csv(file="~/Desktop/scicomm_data_joined.csv", final_join)
```
