---
title: "sci_comm_demographics"
author: "Victoria"
date: "4/23/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
#import data
disc<-read.csv("~/Documents/projects/scicomm_analysis_Arik/data/cleaned_complete_joins/scicomm_complete_data_joined.csv")
disc<-mutate_all(disc, list(~na_if(.,"")))

#recode a few levels
disc$first_gen<-recode(disc$first_gen, "true" = "1")
disc$urm<-recode(disc$urm, "true" = "1", "false" = "0")
disc$low_income<-recode(disc$low_income, "true" = "1")

```

```{r}
#demographic stats overview 
#all students 
disc %>%
    group_by(group, id) %>% 
        top_n(1,survey) %>% #takes only one survey (=row) per student,for students that have both
    ungroup() %>%
    group_by(group) %>%
    summarise(n = n(),
              percent_transfer = (sum(admit_level == "Transfer", na.rm = T)/n)*100, 
              percent_urm = (sum(urm == "1" , na.rm = T)/n)*100,
              percent_female = (sum(gender == "F",  na.rm = T)/n)*100, 
              percent_first_gen =  (sum(first_gen == "1",  na.rm = T)/n)*100,
              percent_low_income = (sum(low_income == "1",  na.rm = T)/n)*100, 
              avg_gpa_prior = mean(gpa_prior))

#ethnicity 
disc %>%
    group_by(group, id) %>% 
        top_n(1,survey) %>% #takes only one survey (=row) per student,for students that have both
    ungroup() %>%
    group_by(group, ethnicity) %>%
    summarise(n = n())

#paired students only 

#create paired students dataframe
paired<- disc %>%
    filter(both_surveys == "y") %>% #must have both surveys. 
    group_by(group, id) %>% 
        top_n(1,survey) #takes only one survey (=row) per student,for students that have both

#demographic percentages for paired: 
paired %>%
    group_by(group) %>%
    summarise(n = n(),
              percent_transfer = (sum(admit_level == "Transfer", na.rm = T)/n)*100, 
              percent_urm = (sum(urm == "1" , na.rm = T)/n)*100,
              percent_female = (sum(gender == "F",  na.rm = T)/n)*100, 
              percent_first_gen =  (sum(first_gen == "1",  na.rm = T)/n)*100,
              percent_low_income = (sum(low_income == "1",  na.rm = T)/n)*100, 
              avg_gpa_prior = mean(gpa_prior))

#ethnicity (can do the same for class_level_prior)
paired %>% 
    group_by(group, ethnicity) %>%
    summarise(n = n())
```
```{r chi squared tests}
#check for differences in demographics between groups: 

hist(disc$gpa_prior) #normal enough
pairwise.t.test(disc$gpa_prior, disc$group) #prior gpa does not significantly differ between control and treatment

#chi squared tests show no difference in likelihood to be in control or treatment given low income, first gen, or urm 
chisq.test(disc$group, disc$low_income, correct=FALSE)
chisq.test(disc$group, disc$first_gen, correct=FALSE)
chisq.test(disc$group, disc$urm, correct=FALSE)

#paired chi squared only 
chisq.test(paired$group, paired$low_income, correct=FALSE) #p = 0.554
chisq.test(paired$group, paired$first_gen, correct=FALSE) #p = 0.215
```
```{r TA/section split}
#how are students allocated across sections and TAs?

#create vectors of each TA's sections 
#found in emails to Dianna, spring 2019 
aarushi <- c("NPB 101D 001 SQ 2019","NPB 101D 002 SQ 2019","NPB 101D 004 SQ 2019")
arik <- c("NPB 101D 003 SQ 2019","NPB 101D 006 SQ 2019","NPB 101D 009 SQ 2019")
victoria <- c("NPB 101D 005 SQ 2019","NPB 101D 007 SQ 2019","NPB 101D 008 SQ 2019")
 
#assign sections to TA 
disc <-disc %>%
    mutate( TA = case_when(
        section %in% aarushi ~ "AG", 
        section %in% arik ~ "AD", 
        section %in% victoria ~ "VF"))
        

#look at split across TAs: 

disc %>%
    #filter(both_surveys == "y") %>%  #uncomment this line to run for only paired students 
    group_by(group, id) %>% 
        top_n(1,survey) %>% #takes only one survey (=row) per student,for students that have both
    ungroup() %>%
    select(group, section, TA) %>%
    group_by(group) %>%
    mutate(n = n()) %>% #sample size per group
    ungroup() %>%
    group_by(group,TA) %>%
    summarise(n_section = n(),  #sample size per group*TA
              n_group = mean(n),  #sample size of group
              percent_TA = n_section/n_group *100) #percent of sample size in that TA. 
```


