---
title: "Fig.2 Science Identity Question Groupings WITHIN-Groups"
output: html_notebook
---
```{r data setup}
library(tidyverse)
setwd("~/Documents/teaching/science_communication_data/github/sci-comm-data-analysis/") #set working directory

#import data, functions, ggplot themes
source("scicomm_datasets.R")
source("scicomm_plot_themes.R")
source("scicomm_functions.R") 
```
```{r between-group plots}
#Survey Scores by Question Groupings WITHIN-GROUPS

#barplot with  means + confidence intervals, "old" figure
scid %>% 
  filter(survey=="change") %>% 
  filter(question %in% qgroupings) %>%
  group_by(question, group) %>% 
  summarise(smean = mean(value, na.rm = TRUE),  #summary statistics for each Q
            ssd = sd(value, na.rm = TRUE),
            count = n()) %>%
  mutate(se = ssd / sqrt(count),
         lower_ci = lower_ci(smean, se, count),
         upper_ci = upper_ci(smean, se, count)) %>%
  group_by(question) %>%
  ggplot(aes(x=as.factor(question), y= as.numeric(smean), fill = group)) + 
  geom_bar(stat="identity", position = position_dodge(), color = "black")+ 
  geom_errorbar(aes(ymax=upper_ci,ymin=lower_ci),position=position_dodge(0.9), width=0.7)+
  geom_segment(aes(x=2.75, y=12, xend=3.25, yend=12))+ #significance bar for community
  annotate("text", x = 3, y = 12.25, label = "**")+
  geom_segment(aes(x=3.75, y=6, xend=4.25, yend=6))+ #significance bar for tools
  annotate("text", x = 4, y = 6.25, label = "**")+
  labs(x="Survey", y="Change in score")+
  scale_fill_manual(name= "Group", labels = c("Control\n(n=25)", "Treatment\n(n=22)"), values = c("skyblue2", "lightgoldenrod"))+ 
  scale_x_discrete(labels=c("Community", "Confidence", "Identity", "Tools & Abilities"))+
  ggtitle("Changes in Science Identity Score Within-Groups")+
  theme_bw()


#boxplots with individual points 
scid %>% 
  filter(survey=="change") %>% 
  filter(question %in% qgroupings) %>%
  group_by(question, group) %>% 
  ggplot(aes(x=as.factor(question), y= perc, fill = group)) + 
  geom_point(aes(color = group), position = position_jitterdodge(), show.legend = F)+ 
  geom_boxplot(alpha = 0.4, outlier.shape = NA) + 
  geom_segment(aes(x=2.75, y=45, xend=3.25, yend=45))+ #significance bar for community
  annotate("text", x = 3, y = 45.25, label = "**")+
  geom_segment(aes(x=3.75, y=35, xend=4.25, yend=35))+ #significance bar for tools
  annotate("text", x = 4, y = 35.25, label = "**")+
  labs(x="Survey", y="Change in percent of total possible score \n(post-pre)")+
  scale_fill_manual(name= "Group", labels = c("Control\n(n=25)", "Treatment\n(n=22)"), values = group.colors)+ 
  scale_x_discrete(labels=qgroup.labels)+
  scale_color_manual(values = group.colors)+
  ggtitle("Changes in Science Identity Score Within-Groups")+
  plot_design

```
```{r t-tests}
#t-tests of change in % scores WITHIN each group for each question grouping 
#with estimates now in percentages

qgroups_within_ttests <- scid %>% 
  filter(survey =="change")%>% 
  filter(question %in% qgroupings)%>%
  nest(-question) %>%  #run model on each level of question
  mutate(fit = map(data, ~ t.test(perc ~ group, data = .)), #t-test formula 
         results = map(fit, glance)) %>% #broom functions
  unnest(results) %>%
  arrange(question) %>% #list in ascending order of p-value
  select(-data, - fit)
  
qgroups_within_ttests
```



