---
title: "Individual Question Analysis"
output: html_notebook
---
```{r data setup, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(ggsignif)
sc<-read.csv(file="~/Desktop/data/scicomm_data_joined.csv") #import joined file

#import functions for confidence intervals 
#functions from: https://community.rstudio.com/t/computing-confidence-intervals-with-dplyr/31868
lower_ci <- function(mean, se, n, conf_level = 0.95){
  lower_ci <- mean - qt(1 - ((1 - conf_level) / 2), n - 1) * se
}
upper_ci <- function(mean, se, n, conf_level = 0.95){
  upper_ci <- mean + qt(1 - ((1 - conf_level) / 2), n - 1) * se
}

#ggplot plot design for all plots 
plot_design<- theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5) )+
  theme_classic()
```

```{r scicomm score and long form data, include=FALSE, warning = FALSE, message = FALSE}
#importing code for scicomm score and long form data from other .Rmd file 

#scicomm score 
sc<-sc %>%
   replace(is.na(.), 0) %>% #change to 0 for ease of math 
   mutate(scicommscore_begin = rowSums(.[23:45]), 
          scicommscore_final = rowSums(.[66:88]), 
          scicommscore_change = scicommscore_final - scicommscore_begin) 
sc[sc == 0] <- NA  #return 0 to NA

```

```{r long dataset, echo = FALSE, warning = FALSE, message = FALSE}
#scid dataset creation (long form of dataset with scicomm data only)
scid<-sc %>% 
 select(id, group,scientist_begin:tellstory_begin, scientist_final:tellstory_final, scicommscore_begin:scicommscore_change)%>%
  gather(question, value, scientist_begin:scicommscore_change)%>%
  separate(col = question, into = c("question", "survey"), sep = "_") 
#minor clean up 
scid$survey<-as.factor(scid$survey) #as factor
scid$question<-as.factor(scid$question)
```

```{r t-tests w/ p values, echo = FALSE, warning = FALSE, message = FALSE}
#t-test contrasts will be after the class and activity, so using final survey data only for t-tests
#filter dataset by final survey:
scid_end<- scid %>%
  filter(survey == "final")

#t-tests compare final survey score by group (treatment or control)
t_tests_post<-with(scid_end,
       by(scid_end, question,
          function(x) t.test(value ~ group, data=x)
       )
     )

#create a data table with all p-values for t-tests
pvals_post <- lapply(t_tests_post, function(x) x$p.value) #extracts p-values from the above t-tests list
pvals_post <- data.frame(matrix(unlist(pvals_post), nrow=length(pvals_post), byrow=T)) #create dataframe 
pvals_post$question<-as.factor(names(t_tests_post)) #extracts the names of each question in the t-test
colnames(pvals_post)<- c("pval", "question") #rename columns for interpretability
pvals_post$pval<-as.numeric(pvals_post$pval)
pvals_post<-pvals_post[order(pvals_post$pval),] #sorts data frame by p-value in ascending order

pvals_post %>%
  filter(pval< 0.06) #returns the questiosn that had a pvalue less than 0.06 
```

```{r}
scid%>%
  filter(question=="commlay2", survey!="change")%>%
  group_by(group, survey)%>%
  summarise(smean = mean(value, na.rm = TRUE),
            ssd = sd(value, na.rm = TRUE),
            count = n()) %>%
  mutate(se = ssd / sqrt(count),
         lower_ci = lower_ci(smean, se, count),
         upper_ci = upper_ci(smean, se, count)) %>%
ggplot( aes(x=as.factor(group), y= as.numeric(smean), fill=survey)) +
  geom_bar(stat="identity", position = position_dodge(), color = "black")+
  geom_errorbar(aes(ymax=upper_ci,ymin=lower_ci),position=position_dodge(0.9), width=0.7)+
  ylim(0,10)+
  labs(x="Survey", y="Identity score")+
  scale_fill_manual(labels = c("Pre", "Post"), values = c("gray", "lightblue"))+
  ggtitle(" 'I can communicate physiological concepts to a lay person' ")+
  plot_design

scid%>%
  filter(question=="tools", survey!="change")%>%
  group_by(group, survey)%>%
  summarise(smean = mean(value, na.rm = TRUE),
            ssd = sd(value, na.rm = TRUE),
            count = n()) %>%
  mutate(se = ssd / sqrt(count),
         lower_ci = lower_ci(smean, se, count),
         upper_ci = upper_ci(smean, se, count)) %>%
ggplot( aes(x=as.factor(group), y= as.numeric(smean), fill=survey)) +
  geom_bar(stat="identity", position = position_dodge(), color = "black")+
  geom_errorbar(aes(ymax=upper_ci,ymin=lower_ci),position=position_dodge(0.9), width=0.7)+
  ylim(0,10)+
  labs(x="Survey", y="Identity score")+
  scale_fill_manual(labels = c("Pre", "Post"), values = c("gray", "lightblue"))+
  ggtitle(" 'I have the tools needed to communicate scientific ideas' ")+
  plot_design

scid%>%
  filter(question=="importscicomm", survey!="change")%>%
  group_by(group, survey)%>%
  summarise(smean = mean(value, na.rm = TRUE),
            ssd = sd(value, na.rm = TRUE),
            count = n()) %>%
  mutate(se = ssd / sqrt(count),
         lower_ci = lower_ci(smean, se, count),
         upper_ci = upper_ci(smean, se, count)) %>%
ggplot( aes(x=as.factor(group), y= as.numeric(smean), fill=survey)) +
  geom_bar(stat="identity", position = position_dodge(), color = "black")+
  geom_errorbar(aes(ymax=upper_ci,ymin=lower_ci),position=position_dodge(0.9), width=0.7)+
  ylim(0,10)+
  labs(x="Survey", y="Identity score")+
  scale_fill_manual(labels = c("Pre", "Post"), values = c("gray", "lightblue"))+
  ggtitle(" 'Communicating scientific knowledge to the public is an important aspect of being a science student' ")+
  plot_design
```
```{r}
#the following code returns the p-values for each question for a t-test of pre versus post scores for the treatment group

#filter dataset by treatment group only
scid_trt<- scid %>%
  filter(group == "Treatment", survey!="change")

#t-tests compare final survey score by group (treatment or control)
t_tests_trt<-with(scid_trt,
       by(scid_trt, question,
          function(x) t.test(value ~ survey, data=x)
       )
     )

#create a data table with all p-values for t-tests
pvals_trt <- lapply(t_tests_trt, function(x) x$p.value) #extracts p-values from the above t-tests list
pvals_trt <- data.frame(matrix(unlist(pvals_trt), nrow=length(pvals_trt), byrow=T)) #create dataframe 
pvals_trt$question<-as.factor(names(t_tests_trt)) #extracts the names of each question in the t-test
colnames(pvals_trt)<- c("pval", "question") #rename columns for interpretability
pvals_trt$pval<-as.numeric(pvals_trt$pval)
pvals_trt<-pvals_trt[order(pvals_trt$pval),] #sorts data frame by p-value in ascending order

v2<- pvals_trt %>%
  filter(pval< 0.06) #returns the questiosn that had a pvalue less than 0.06 
```

```{r}
#the following code returns the p-values for each question for a t-test of pre versus post scores for the treatment group

#filter dataset by treatment group only
scid_cntrl<- scid %>%
  filter(group == "Control", survey!="change")

#t-tests compare final survey score by group (treatment or control)
t_tests_cntrl<-with(scid_cntrl,
       by(scid_cntrl, question,
          function(x) t.test(value ~ survey, data=x)
       )
     )

#create a data table with all p-values for t-tests
pvals_cntrl <- lapply(t_tests_cntrl, function(x) x$p.value) #extracts p-values from the above t-tests list
pvals_cntrl <- data.frame(matrix(unlist(pvals_cntrl), nrow=length(pvals_cntrl), byrow=T)) #create dataframe 
pvals_cntrl$question<-as.factor(names(t_tests_cntrl)) #extracts the names of each question in the t-test
colnames(pvals_cntrl)<- c("pval", "question") #rename columns for interpretability
pvals_cntrl$pval<-as.numeric(pvals_cntrl$pval)
pvals_cntrl<-pvals_cntrl[order(pvals_cntrl$pval),] #sorts data frame by p-value in ascending order

v1<- pvals_cntrl %>%
  filter(pval< 0.06) #returns the questiosn that had a pvalue less than 0.06 
```


Resources used: 
https://stackoverflow.com/questions/30332752/how-to-perform-t-tests-for-each-level-of-a-factor-with-tapply
https://stackoverflow.com/questions/35194782/convert-output-from-multiple-t-tests-to-data-frame
https://stackoverflow.com/questions/4227223/convert-a-list-to-a-data-frame
