---
title: "SciComm Qualitative Coding Analysis"
author: "Victoria"
date: "4/30/2020"
output: html_document
 df_print: paged
---
```{r data setup}
library(tidyverse)
#import coded sentences
lines<-read.csv("~/Documents/projects/scicomm_analysis_Arik/data/treatment_reflections_sentences_coded.csv",na.strings=c("","NA"))
ctrl_lines<-read.csv("~/Documents/projects/scicomm_analysis_Arik/qualitative_coding/control_reflections_coded.csv", na.strings = c("", "NA"))
```

```{r combine treatment and control}
#check column names match
colnames(lines) == colnames(ctrl_lines)

#combine two dataframes 
lines_all <-rbind(lines, ctrl_lines)
```

```{r collapse sentences into single reflections}
#collapse into one student reflection per week (ex: a student who did all 5 should have 5 lines in df total)
codes_all<-
lines_all %>%
  select(-sis_login_id, -section, -reflection_text, - group) %>%
  mutate_all(~replace(., is.na(.), 0)) %>% #replace NA with 0 for sum purposes
 group_by( id, response_no) %>% summarise_all(funs(sum)) 

#grab groups for a join with the collapsed reflections
groups <- lines_all %>%
  select(id, group) %>% 
  distinct(id,.keep_all = TRUE) 

#join collapsed sentences with groups
codes <- inner_join(groups, codes_all, by = "id")


#how many reflections have a theme occuring more than once (i.e. more than one sentence had a theme)?
codes %>%
  rowwise %>%
  mutate(numtwos = sum(c(neutral,negative, class_metacog, gaps_knowledge, comm_metacog, contextualize, positive, negative) > 1)) %>% #for theme columns, count how many have counts > 1
  group_by(response_no) %>%
  summarise(n = n(), 
            n_multiple_codes = sum(numtwos > 0)) %>% #totals by response
  summarise_all(funs(sum)) #gives overall total

```

```{r create presence/absence df}
#take collapsed dataframe and convert to yes/no to presence/absence of each theme 
codes_binary <-
codes %>%
  group_by(id, response_no) %>%
   mutate_if(is.numeric, ~1 * (. != 0)) #create a binary y/n whether they expressed that theme 
```

```{r sample size}
#sample size of reflections  and students 
lines_all %>%
  group_by(group, response_no) %>%
  summarise(n_sentences = n(), 
            n_students = n_distinct(id)) #%>%
  #summarise_all(funs(sum))  #run this line to get column totals. 
```

```{r count presence of themes across reflection}
#count of each "theme" across reflections 
codes_binary %>%
  select(-id) %>%
  group_by(group, response_no)%>%
  mutate(n_students = n())%>%
  group_by(group, response_no, n_students) %>%
  summarise_all(funs(sum)) %>%
  select(-id)

#need to convert to %s as seen in previous dataframes 
themes_percents<- 
  codes_binary %>%
    group_by(group, response_no) %>%
    summarise(n = n(),
              perc_neutral = (sum(neutral, na.rm = T)/n)*100, 
              perc_class_metacog = (sum(class_metacog , na.rm = T)/n)*100,
              perc_gaps_knowledge = (sum(gaps_knowledge,  na.rm = T)/n)*100, 
              perc_comm_metacog =  (sum(comm_metacog,  na.rm = T)/n)*100,
              perc_contextualize = (sum(contextualize,  na.rm = T)/n)*100, 
              perc_positive = (sum(positive,  na.rm = T)/n)*100,
              perc_negative = (sum(negative,  na.rm = T)/n)*100) 

#theme percents in long form for ggplots. 
theme_perc_long <- 
  themes_percents %>%
  select(-n) %>%
  pivot_longer(cols = perc_neutral:perc_negative, names_to = "theme", values_to = "percent") %>%
  mutate(theme = gsub( "perc_", "", as.character(theme))) %>% #get rid of perc_ header in theme names 
  mutate_if(is.character, as.factor) #convert back to factor 

#ALL themes (across all responses)
all_themes<- 
  codes_binary %>%
    group_by(group) %>%  #no more group by response no
    summarise(n = n(),
              perc_neutral = (sum(neutral, na.rm = T)/n)*100, 
              perc_class_metacog = (sum(class_metacog , na.rm = T)/n)*100,
              perc_gaps_knowledge = (sum(gaps_knowledge,  na.rm = T)/n)*100, 
              perc_comm_metacog =  (sum(comm_metacog,  na.rm = T)/n)*100,
              perc_contextualize = (sum(contextualize,  na.rm = T)/n)*100, 
              perc_positive = (sum(positive,  na.rm = T)/n)*100,
              perc_negative = (sum(negative,  na.rm = T)/n)*100) 

# long form for ggplots. 
all_themes_long <- 
  all_themes %>%
  select(-n) %>%
  pivot_longer(cols = perc_neutral:perc_negative, names_to = "theme", values_to = "percent") %>%
  mutate(theme = gsub( "perc_", "", as.character(theme))) %>% #get rid of perc_ header in theme names 
  mutate_if(is.character, as.factor) #convert back to factor 

#send to .csv for Natalia to make graphs in SAS 
write.csv(all_themes_long,"~/Desktop/all_themes_percents_long.csv")
write.csv(all_themes,"~/Desktop/all_themes_percents.csv")

```

```{r theme plots assgn 1 2 4 }
#view assignments 1, 2, 4 as bar graphs 

#across assignments: 
theme_perc_long %>%
  filter(response_no %in% c(1,2,4)) %>%
  ggplot(aes(x = theme, y = percent, fill = as.factor(response_no))) + 
  geom_col(position = position_dodge(0.9)) + 
  facet_grid(cols = vars(response_no), rows = vars(group))

#across themes: 
assgn124<-
  theme_perc_long %>%
  filter(response_no %in% c(1,2,4)) %>%
  filter(theme != "neutral") %>%
  ggplot(aes(x = as.factor(response_no), y = percent, fill = theme)) + 
  geom_col(position = position_dodge(0.9), color = "black") + 
  ylim(0,100)+ 
  scale_x_discrete(labels = c("Teach", "Tweet", "Creative/Art"))+ 
  labs(x = NULL, y = "Percent of responses where theme was present") + 
  facet_grid(cols = vars(theme), rows = vars(group)) + 
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none")


ggsave("~/Desktop/assgn124.png", assgn124, height = 7, width = 7, units = "in")
```

```{r theme plot assgn 1 3 5}
#theme plot for numbers 1, 3, 5 (teaching assignment)
#across themes: 
assgn135 <- 
  theme_perc_long %>%
  filter(theme != "neutral") %>%
  ggplot(aes(x = as.factor(response_no), y = percent, fill = theme)) + 
  geom_col(position = position_dodge(0.9), color = "black") + 
  ylim(0,100)+ 
  labs(x = "Time students completed assignment", y = "Percent of responses where theme was present") + 
  facet_grid(cols = vars(theme), rows = vars(group)) + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none")
  

```
### Statistics:  Binomial GLMMs

```{r setup for stats}
library(lme4)
library(lmerTest)
library(sjPlot)
library(ggeffects)

#create "time" variable (what was the "time students had seen the assignment?)
codes_binary<- codes_binary %>%
  mutate(time = case_when(
    response_no == 3 ~ 2, 
    response_no == 5 ~ 3, 
    TRUE ~ 1
  )) %>%
    mutate(assignment = case_when(
    response_no == 2 ~ "tweet", 
    response_no == 4 ~ "art", 
    TRUE ~ "teach"
  ))
  

#long form so that theme can be a variable
codes_bin_long<-
codes_binary %>%
  pivot_longer(neutral:negative, names_to = "theme", values_to = "present") 

codes_bin_long$theme<-as.factor(codes_bin_long$theme)
codes_bin_long$theme<-relevel(codes_bin_long$theme, "neutral") #set neutral as first level of assignment
```

```{r stats: effect of time }
m_time <-glmer(present ~ theme*response_no + (1|id), data=codes_bin_long, family = "binomial")
summary(m_time)

m_theme <-glmer(present ~ theme*group + (1|id), data=codes_bin_long, family = "binomial")
summary(m_theme)

gaps <- codes_bin_long %>% filter(theme == "gaps_knowledge")
m_gaps <-glmer(present ~ group*response_no + (1|id), data=gaps, family = "binomial")
summary(m_gaps)

class_meta<- codes_bin_long %>% filter(theme == "class_metacog")
m_class <-glmer(present ~ group*response_no + (1|id), data=class_meta, family = "binomial")
summary(m_class)

class_meta_135<- codes_bin_long %>% filter(theme == "class_metacog") %>% filter(response_no %in% c(1,3,5))
m_class_135 <-glmer(present ~ group*response_no + (1|id), data=class_meta_135, family = "binomial")
summary(m_class_135)

#difference responses 

pr_class <- ggpredict(m_class, c("response_no", "group"), type = "re")
plot(pr_class)

#illustrates the difference in responses over time for the theme 
  theme_perc_long %>%
  filter(theme == "class_metacog") %>%
  ggplot(aes(x = as.factor(response_no), y = percent, color = group)) + 
  geom_point(position = position_dodge(0.9), color = "black") + 
  geom_line(aes(group = group)) + 
  ylim(70,100)+ 
  labs(x = "Response number", y = "Percent of responses where theme was present") + 
  facet_grid(cols = vars(theme), rows = vars(group)) + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none")
  
```

```{r stats: teaching assignments }
teach<-codes_bin_long %>% filter(assignment == "teach" & group == "Treatment")

#relationship between time and theme
m1<-glmer(present ~ theme*time +  (1|id), data=teach, family = "binomial") 
summary(m1)

pr1 <- ggpredict(m1, c("theme", "time"), type = "re")
plot(pr1)
```

```{r stats all assignments}
m3<-glmer(present ~ theme*response_no +  (1|id), data=codes_bin_long, family = "binomial") 
summary(m3)

pr3 <- ggpredict(m3, c("response_no", "theme"), type = "re")
plot(pr3)
```


```{r stats different assignments}
#relationship between assignment and theme (first time)
assgn<-codes_bin_long %>% filter(time == 1)

assgn$assignment<-as.factor(assgn$assignment)
assgn$assignment<-relevel(assgn$assignment, "teach")

m2<-glmer(present ~ theme*assignment +  (1|id), data=assgn, family = "binomial") 
summary(m2)

pr2 <- ggpredict(m2, c("theme", "assignment"), type = "re")
plot(pr2)

```

```{r stats last TEACH vs other assignents}
#does this relationship still hold when comparing the last teaching assignment to the other assignments?

lastteach<-codes_bin_long %>% filter(response_no %in% c(2,4,5))

lastteach$assignment<-as.factor(lastteach$assignment)
lastteach$assignment<-relevel(lastteach$assignment, "teach") 

m4<-glmer(present ~ theme*assignment +  (1|id), data=lastteach, family = "binomial") 
summary(m4)

pr4 <- ggpredict(m4, c("theme", "assignment"), type = "re")
plot(pr4)

```
```{r}
library(lme4)

glm1<-
codes_bin_long %>%
  filter( theme != "comm_metacog") %>%
  glmer(present ~ theme*group + (1|id), data = ., family = "binomial") 

summary(glm1)

glm2<-
codes_bin_long %>%
  filter( theme != "comm_metacog") %>%
  glm(present ~ theme*group, data = ., family = "binomial") 

summary(glm2)
```
```{r}
#chi-squared tests for each theme 

#class metacognition 
table2<- table(codes_binary$group, codes_binary$class_metacog)
prop.table(table2,1)
chisq.test(table2,correct=FALSE)

#comm metacognition
table3<- table(codes_binary$group, codes_binary$comm_metacog)
prop.table(table3,1)
chisq.test(table3,correct=FALSE)

#gaps in knowledge
table4<- table(codes_binary$group, codes_binary$gaps_knowledge)
prop.table(table4,1)
chisq.test(table4,correct=FALSE)

#contextualization
table5<- table(codes_binary$group, codes_binary$contextualize)
prop.table(table5,1)
chisq.test(table5,correct=FALSE)

#positive
table6<- table(codes_binary$group, codes_binary$positive)
prop.table(table6,1)
chisq.test(table6,correct=FALSE)

#negative
table7<- table(codes_binary$group, codes_binary$negative)
prop.table(table7,1)
chisq.test(table7,correct=FALSE)
```


### Resoures used
[Count number of values in row using dplyr](https://stackoverflow.com/questions/37731987/count-number-of-values-in-row-using-dplyr)
[gsub for string split](https://stackoverflow.com/questions/14718203/removing-particular-character-in-a-column-in-r)
[Chi-square in R](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/PH717-QuantCore/PH717-Module8-CategoricalData/PH717-Module8-CategoricalData4.html)



