---
title: "SciComm project: Text Analysis"
output: html_notebook
---
```{r data setup, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)

sc.text<-read.csv(file="~/Documents/projects/scicomm_analysis_Arik/qualitative_coding/treatment_assignment_responses.csv")
```

```{r treatment split into lines, echo=FALSE}
#split text into lines (one line per line), but maintains the id / group / response week
#separates lines based on the period
sc_responses_lines  <- separate_rows(sc.text, reflection_text, sep="\\.") 
#separate again on the exclamation and new line
sc_responses_lines_2  <- separate_rows(sc_responses_lines, reflection_text, sep="!")
sc_responses_lines_2  <- separate_rows(sc_responses_lines_2, reflection_text, sep="\n") 

#write dataframe to a file for future coding 
sc_responses_lines3 <- sc_responses_lines_2 %>% filter(reflection_text != "") #remove the blank rows
write.csv(sc_responses_lines3, "~/Desktop/test.csv")
```
```{r control split into lines, echo=FALSE}
#control data 
control<-read.csv("~/Documents/projects/scicomm_analysis_Arik/qualitative_coding/control_responses_reflections_only_AD.csv")

#split text into lines (one line per line), but maintains the id / group / response week
#separates lines based on the period
control_lines  <- separate_rows(control, response_text, sep="\\.") 
#separate again on the exclamation and new line
control_lines_2  <- separate_rows(control_lines, response_text, sep="!")
control_lines_2  <- separate_rows(control_lines_2, response_text, sep="\n")

#write dataframe to a file for future coding 
control_lines3 <- control_lines_2 %>% filter(response_text != "") #remove the blank rows
write.csv(control_lines3, "~/Desktop/test.csv")
```


```{r matching colnames for rbind}
#append together treatment and control responses for word count analysis 

#rename columns in control dataframe so they match the treatment dataframe
control_new <- control %>%
  rename( id = ID, 
          sis_login_id = SIS.Login.ID, 
          section = Section, 
          group = Group.Assignment,
          reflection_text = response_text)

#delete unnecessary columns 
control_new$X <- NULL #get rid of "X" column
sc.text$reflection_yn<-NULL #get rid of y/n column

#check that both column names match 
colnames(sc.text) == colnames(control_new) #should all be true 

#combine datasets 
reflect_all <- rbind(sc.text, control_new) 
```


```{r wordcount analysis }

#count words in each reflection using function
reflect_all$wordcount <- sapply(reflect_all$reflection_text, function(x) length(unlist(strsplit(as.character(x), "\\W+"))))

         
#graph comparing wordcounts by group 
reflect_all %>%
  drop_na(response_no) %>%
  group_by(group,response_no) %>%
  summarise(avg_count = mean(wordcount), 
            sd = sd(wordcount),
            n = n()) %>%
  mutate(se = sd / sqrt(n)) %>%
  ggplot(aes(x=as.factor(response_no), y= avg_count, fill = group, label = round(avg_count, digits = 1))) + 
    geom_bar(stat = "identity", position = position_dodge(0.9), color = "black") + 
    geom_errorbar(aes(ymax=avg_count + se,ymin= avg_count -se),position=position_dodge(0.9), width=0.7) +
  annotate("text", x = 1, y = 115, label = "**", size = 10)+
  annotate("text", x = 3, y = 90, label = "**", size = 10)+
  annotate("text", x = 5, y = 60, label = "**", size = 10)+
  geom_text(vjust = -2, position = position_dodge(0.9)) + 
  ylim(0, 115) +
  scale_fill_manual(values = c("skyblue2", "grey")) + 
  labs(x = "Week of Assignment", y="Average word count of response", subtitle = "Means, bars are SEM") + 
  theme_bw()
```

```{r ttests for wordcount}

#t
r1_teach <- reflect_all %>%
  filter(response_no == "1")

t.test(r1_teach$wordcount ~ r1_teach$group)
wilcox.test(r1_teach$wordcount ~ r1_teach$group)
  

r3_teach <- reflect_all %>%
  filter(response_no == "3")

t.test(r3_teach$wordcount ~ r3_teach$group)
wilcox.test(r3_teach$wordcount ~ r3_teach$group)

r5_teach <- reflect_all %>%
  filter(response_no == "5")

t.test(r5_teach$wordcount ~ r5_teach$group)
wilcox.test(r5_teach$wordcount ~ r5_teach$group)

#linear model for effect of treatment & time 
m1 <- lm(wordcount ~ group*response_no, data = reflect_all)
summary(m1)
```