---
title: "Science Communication Data Analysis"
output: html_notebook
---

```{r}
library(tidyverse)
# fin<-read.csv("~/Desktop/data/scicomm_final_survey_numeric.csv")
# begin<-read.csv("~/Desktop/data/scicomm_initial_survey.csv")
# grades<-read.csv("~/Desktop/data/scicomm_course_grades.csv")
# groups<-read.csv("~/Desktop/data/scicomm_group_assgn.csv")

fin<-read.csv("~/Documents/projects/scicomm_analysis_Arik/data/scicomm_final_survey_numeric.csv")
begin<-read.csv("~/Documents/projects/scicomm_analysis_Arik/data/scicomm_initial_survey.csv")
grades<-read.csv("~/Documents/projects/scicomm_analysis_Arik/data/scicomm_course_grades.csv")
groups<-read.csv("~/Documents/projects/scicomm_analysis_Arik/data/scicomm_group_assgn.csv")

```

### Data cleanup / filtering 

```{r}
students<-left_join(groups,grades, by = "id") #join experimental groups and grades
students$group<-as.factor(students$group)
students$grade_final<-as.numeric(students$grade_final)

students<- students[c(-4, -6,-7,-8,-9,-10,-11,-13,-14)] #clean up excessive columns in students

#filter any mismatch ids in begin and end survey data

students %>%
  group_by(group) %>%
  drop_na(grade_final)%>%
  summarize(n=n(), avg_grade = mean(grade_final), sd = sd(grade_final)) #sample size and average grade
```
### Evaluation criteria 
Filtered out observations that took less than 3 minutes to take the survey or entered a mismatching student id (making accurate joins difficult).

```{r}
#rename id column to sis_id
colnames(fin)[11]<-"sis_id" #rename 
colnames(begin)[11]<-"sis_id" #rename columns

#check if student id entries match in survey data
fin$id_match <- ifelse(fin$sis_id==fin$sis_id_2,"TRUE","FALSE")
begin$id_match <-ifelse(begin$sis_id==begin$sis_id_2, "TRUE", "FALSE")

#filter out observations that took less than 3 minutes to take survey or entered a mismatching id
begin2<-begin %>%
  filter(duration_sec > 180 & id_match==TRUE) #121 observations
fin2<-fin %>%
  filter(duration_sec > 180 & id_match==TRUE) #77 observations

#begin joins 

#convert columns we are joining by to factors 
students$sis_id<-as.factor(students$sis_id)
begin2$sis_id<-as.factor(begin2$sis_id)
fin2$sis_id<-as.character(fin2$sis_id)

test<-left_join(students,begin2, by="sis_id")
test2<-left_join(test, fin2, by="sis_id") #there are a lot of empty rows in this join

#remove empty rows from join
final_join<-test2 %>%
  filter(full_name.x !="") #215 observations remain

#rename columns for interpretability
colnames(final_join)
#any joined columns with a .y (meaning from the final dataset) renamed as _final
colnames(final_join)<-str_replace(colnames(final_join), "[.]y", "_final")
#any joined columns with a .x (meaning from the begin dataset) renamed as _final
colnames(final_join)<-str_replace(colnames(final_join), "[.]x", "_begin")
#rename a few more columns 
colnames(final_join)[1]<-"name"
colnames(final_join)[10]<-"total_grade"

#create a column that says if survey was completed - is there are start date to the survey?
final_join$begin_survey_complete<-ifelse(is.na(final_join$start_date_begin), "n", "y")
final_join$final_survey_complete<-ifelse(is.na(final_join$start_date_final), "n", "y")

#number and perc of students that completed both surveys, per group
final_join %>%
  group_by(group,begin_survey_complete, final_survey_complete) %>%
  summarize(n=n()) #sample size and average grade

#send final, joined dataset to a csv file (ONLY RUN ONCE)
write.csv(file="~/Desktop/scicomm_data_joined.csv", final_join)
```

```{r, eval = FALSE}
#Not sure what this is as sc is not initialized in this file... 
# colnames(sc)
# colnames(sc)[13]<-"startdate_begin"
# colnames(sc)[56]<-"startdate_final"
# colnames(sc)[14]<-"enddate_begin"
# colnames(sc)[57]<-"enddate_final"
# colnames(sc)[16]<-"ipaddress_begin"
# colnames(sc)[59]<-"ipaddress_final"
```