---
title: "Fig. 4 : Assignment Attitudes "
output: html_notebook
---
Q10 and Q12 on the final qualtrics survey. 

```{r data setup}
library(tidyverse)
setwd("~/Documents/GitHub/sci-comm-data-analysis/") #set working directory

#import data, functions, ggplot themes
source("scicomm_datasets.R")
source("scicomm_plot_themes.R")
source("scicomm_functions.R") 
```

```{r assignment questions, echo=FALSE, message=FALSE, warning=FALSE}
#Q10 on the qualtrics survey are coded strangely, need to be scaled to interpretable numbers.
#Q10 ($assignment) ranges 18 - 24. Subtract 17 to make it range 1 - 7. 
sc$assignment <- (sc$assignment - 17) 

#Q12 ranges 4 - 10. Subtract 3 to make range 1- 7. 
sc$future_assgn <- (sc$future_assgn - 3) 

###PLOT

#likert labels for plots 

likert.labels <-c("Strongly Disagree", "Disagree", "Somewhat Disagree", "Neither agree nor disagree", "Somewhat Agree", "Agree", "Strongly Agree" )

#question labels for the facet_wrap labeller function 

q10q12<-c("The biweekly assignments were beneficial for my learning", "I would like to have exercises that are similar to the biweekly assignments in other courses")
names(q10q12) <- c("assignment","future_assgn")

#Q10 and Q12 in one plot using facet wrap , y axis now percent of respondents
sc %>%
  select(id, group, assignment, future_assgn) %>%
  tidyr::pivot_longer(assignment:future_assgn, names_to = "question", values_to = "score") %>%
  filter(!is.na(score)) %>%
  mutate(score = as.factor(score)) %>%
  group_by(group) %>%
  mutate(n = n()) %>%
  group_by(group, question, score) %>%
  mutate(perc = case_when(group == "Control" ~ n()/40 ,
                        group == "Treatment" ~ n()/37)) %>%
  group_by(group, question, score) %>%
  summarize(percent = mean(perc)) %>%
  ggplot(aes(x=as.numeric(score),y=(percent*100), fill = group )) + 
  geom_bar(stat = "identity", position = position_dodge(0.9), color = "black")+ 
  scale_fill_manual(name= "Group", labels = c("Control\n(n=40)", "Treatment\n(n=37)"), values = c("grey", "skyblue2")) + 
  scale_x_reverse(name = "Likert score", breaks = (7:1), labels = function(x) str_wrap(likert.labels, width = 10))+ 
  ylab("Percent of total respondents (%)")+
  facet_wrap(~question, nrow = 2, labeller = labeller(question = q10q12)) + 
  theme_bw()

#density plot
```
```{r}
#stats that show the average likert score (note that higher scores mean less agreement the way it was coded)
sc %>%
  select(id, group, assignment, future_assgn) %>%
  tidyr::pivot_longer(assignment:future_assgn, names_to = "question", values_to = "score") %>%
  filter(!is.na(score)) %>%
  group_by(group, question) %>%
  summarise( n = n(), 
             avg = mean(score), 
             sd = sd(score)) 

#boxplots with likert scores
sc %>%
  select(id, group, assignment, future_assgn) %>%
  tidyr::pivot_longer(assignment:future_assgn, names_to = "question", values_to = "score") %>%
  filter(!is.na(score)) %>%
  mutate(score = -score)%>% #to reverse the scores as they were reverse coded
  ggplot(aes(x=question,y=score, fill = group)) + 
  geom_boxplot(outlier.shape = NA, alpha = 0.5) + 
  labs(x="Question", y="Likert Score")+
  scale_x_discrete(labels=c("Assignments beneficial to my learning", "I would like similar exercises"))+
  scale_y_continuous(name = "Likert score", breaks = (-7:-1), labels = function(x) str_wrap(likert.labels, width = 10)) +  #to label with agree/disagree scores
  scale_fill_manual(name = "Group", values = group.colors)+
  scale_color_manual(values = group.colors)+
  ggtitle("Attitude differences between treatment groups")+
  plot_design

#t-tests on each question
assignment_q<-sc %>%
  select(id, group, assignment, future_assgn) %>%
  tidyr::pivot_longer(assignment:future_assgn, names_to = "question", values_to = "score") %>%
  filter(!is.na(score)) %>%
  filter(question =="assignment")

t.test(assignment_q$score ~ assignment_q$group) 

future_q<-sc %>%
  select(id, group, assignment, future_assgn) %>%
  tidyr::pivot_longer(assignment:future_assgn, names_to = "question", values_to = "score") %>%
  filter(!is.na(score)) %>%
  filter(question =="future_assgn")

t.test(future_q$score ~ future_q$group)
```


